### ISSUE TITLE
RuntimeError: CudaError: device-side assert triggered

### ISSUE THREAD

**Issue by Vinit-source** [addtt/attend-infer-repeat-pytorch#1]
![Screenshot (23)](https://user-images.githubusercontent.com/72271049/107178785-f2bac900-69fa-11eb-80c8-06722c9e6ee2.png)
![Screenshot (25)](https://user-images.githubusercontent.com/72271049/107178789-f51d2300-69fa-11eb-8b46-bad677fd2d71.png)

**Comment by addtt** [comment]
Hi! Sorry to hear this is not working for you. Can you try using python 3.7 and running locally? It uses CPU if there's no GPU available. Just let it train for half a minute to see if it goes smooth. I just tried it again from a clean conda environment with python 3.7, installed requirements with pip install -r requirements.txt, and it works. I suggest you try with conda too. If it works locally but not on colab, I'm not sure what the problem might be.

Btw I just updated the requirements to add tensorboard which I had forgotten, but for me it also works without tensorboard installed (in that case it doesn't save logs).

**Comment by fengxyStar** [comment]
Hi. I met the same problem. I found it is mainly due to that **weights of the lstm and the predictor change to NaN**. It makes the output become NaN too and results the error. 
Through the visualization of tensorboard, I found a sudden change of accuracy appeared in the process of training (as shown below, it is noted that the NaN does not appear immediately after the sudden change). After that, the model continues to train for several iterations and the NaN appears suddenly. However, I have no idea why it happened.

<img width="1100" alt="屏幕快照 2021-08-02 下午12 11 04" src="https://user-images.githubusercontent.com/55783894/127803288-d26d371c-de34-49b9-ae72-ade12a7c7599.png">

**Comment by addtt** [comment]
Thanks for looking into this. I never had these problems, but I was using package versions that were around at that time (see requirements.txt). Maybe something changed in the newer versions of PyTorch (or some other package) that make this unstable?

This can typically happen if some activation becomes too large, e.g. when taking the log of something that gets really close to zero. Usually some form of clipping helps (e.g. `log(clip(x, min=1e-4))` or `log(x + 1e-4)`), but I'm still puzzled why I never encountered such problems with this model. It might be useful to save checkpoints every time step (keeping only the last few of them) and then do a post-mortem by loading the last checkpoints and seeing what went wrong. Or logging weights and gradients of all parameters to see exactly where in the network things start to explode.

**Comment by fengxyStar** [comment]
> Thanks for looking into this. I never had these problems, but I was using package versions that were around at that time (see requirements.txt). Maybe something changed in the newer versions of PyTorch (or some other package) that make this unstable?
> 
> This can typically happen if some activation becomes too large, e.g. when taking the log of something that gets really close to zero. Usually some form of clipping helps (e.g. `log(clip(x, min=1e-4))` or `log(x + 1e-4)`), but I'm still puzzled why I never encountered such problems with this model. It might be useful to save checkpoints every time step (keeping only the last few of them) and then do a post-mortem by loading the last checkpoints and seeing what went wrong. Or logging weights and gradients of all parameters to see exactly where in the network things start to explode.

Thank you for your detailed reply! I finally figured out where the NaN results from. At the later stage of training,  the value of `z_pres_p`  can reach 1.0. Although the code defines `z_pres_p.clamp(min=eps, max=1.0-eps)` operation where `eps=1e-12`  ,  but the eps is too small and `z_pres_p` is still equal to 1.0 after the clamp operation (It may be due to the accuracy in GPU floating point calculations. It also explains why you never had the problem ). It makes the derivative of  `kl_pres` become NaN.    **To solve the problem, just let `eps` be no less than 1e-7.**

**Comment by addtt** [comment]
Nice, thank you! So did this solve the problem? Would you mind sending a PR with the change (linked to this issue)?
